#!/usr/bin/env bash
# Auto-run Ansible with inventory & vars generated by Terraform

set -euo pipefail

ANSIBLE_DIR="./ansible"
INVENTORY_FILE="$ANSIBLE_DIR/inventory/hosts"
PLAYBOOK="${1:-site.yml}"       # default playbook
EXTRA_ARGS="${@:2}"

if [[ ! -f "$INVENTORY_FILE" ]]; then
  echo "Error: Inventory not found at $INVENTORY_FILE"
  exit 1
fi

echo "🔧 Using inventory: $INVENTORY_FILE"
echo "🚀 Running playbook: $PLAYBOOK"
echo

ansible-playbook -i "$INVENTORY_FILE" "$ANSIBLE_DIR/playbooks/$PLAYBOOK" $EXTRA_ARGS
