#!/usr/bin/env sh
set -eo pipefail

LXC_ENABLED_NAME=lxc_${1}.tf
LXC_DISABLED_NAME="disabled/lxc_${1}.tf.disabled"

VM_ENABLED_NAME=vm_${1}.tf
VM_DISABLED_NAME="disabled/vm_${1}.tf.disabled"


if test -f $LXC_ENABLED_NAME || test -f $LXC_DISABLED_NAME
then
	ENABLED_NAME=$LXC_ENABLED_NAME
	DISABLED_NAME=$LXC_DISABLED_NAME
else
	ENABLED_NAME=$VM_ENABLED_NAME
	DISABLED_NAME=$VM_DISABLED_NAME
fi

if test -f $DISABLED_NAME
then
	echo "$1 is already disabled or duplicated"
	exit 1
fi

if ! test -f $ENABLED_NAME
then
	echo "$ENABLED_NAME doesn'texist!"
	exit 1
fi

if mv $ENABLED_NAME $DISABLED_NAME
then
	echo "disabled $1"
else
	echo "failed to disable $1"
	exit 1
fi
exit 0
