#!/usr/bin/env sh
# SPDX-License-Identifier: MIT

set -eo pipefail

LXC_ENABLED_NAME=lxc_${1}.tf
LXC_DISABLED_NAME="disabled/lxc_${1}.tf.disabled"

VM_ENABLED_NAME=vm_${1}.tf
VM_DISABLED_NAME="disabled/vm_${1}.tf.disabled"


if test -f $LXC_ENABLED_NAME || test -f $LXC_DISABLED_NAME
then
	ENABLED_NAME=$LXC_ENABLED_NAME
	DISABLED_NAME=$LXC_DISABLED_NAME
else
	ENABLED_NAME=$VM_ENABLED_NAME
	DISABLED_NAME=$VM_DISABLED_NAME
fi

if test -f $ENABLED_NAME
then
	echo "$1 is already enabled or duplicated"
	exit 1
fi

if ! test -f $DISABLED_NAME
then
	echo "Can't access $DISABLED_NAME"
	exit 1
fi
if mv $DISABLED_NAME $ENABLED_NAME
then
	echo "enabled $1"
else
	echo "failed to enable $1"
	exit 1
fi
exit 0
