#!/usr/bin/env sh
set -eo pipefail

ENABLED_NAME=lxc_${1}.tf
DISABLED_NAME="lxc_${1}.tf.disabled"
if test -f $ENABLED_NAME
then
	echo "$1 is already enabled or duplicated"
	exit 1
fi

if ! test -f $DISABLED_NAME
then
	echo "Can't access $DISABLED_NAME"
	exit 1
fi
if mv $DISABLED_NAME $ENABLED_NAME
then
	echo "enabled $1"
else
	echo "failed to enable $1"
	exit 1
fi
exit 0
