#!/usr/bin/env bash


echo -n "Input GITLAB_ACCESS_TOKEN? "
read -s GITLAB_ACCESS_TOKEN
export GITLAB_ACCESS_TOKEN
export TF_STATE_NAME=proxmox-homelab
terraform init \
    -backend-config="address=https://gitlab.crumpton.org/api/v4/projects/20/terraform/state/$TF_STATE_NAME" \
    -backend-config="lock_address=https://gitlab.crumpton.org/api/v4/projects/20/terraform/state/$TF_STATE_NAME/lock" \
    -backend-config="unlock_address=https://gitlab.crumpton.org/api/v4/projects/20/terraform/state/$TF_STATE_NAME/lock" \
    -backend-config="username=bea$USER" \
    -backend-config="password=$GITLAB_ACCESS_TOKEN" \
    -backend-config="lock_method=POST" \
    -backend-config="unlock_method=DELETE" \
    -backend-config="retry_wait_min=5" -reconfigure
    